apiVersion: extensions/v1beta1
kind: Deployment

# https://cloud.google.com/kubernetes-engine/docs/tutorials/persistent-disk

# Log into a container with a proxy connection, make an account and database
# CREATE DATABASE tsugi DEFAULT CHARACTER SET utf8;
# GRANT ALL ON tsugi.* TO 'ltiuser'@'%' IDENTIFIED BY 'ltipassword';

# Make a secret for that database
# kubectl create secret generic tsugi-db-credentials --from-literal=username=ltiuser --from-literal=password=ltipassword
# kubectl create secret generic tsugi-admin-password --from-literal=password=appstore
# kubectl create secret generic tsugi-admin-password --from-literal=password=sha256:eaffb3558916...

# Make the persistent disk
# gcloud compute disks create --size=10GB --type=pd-ssd --zone=us-central1-a tsugi-www

metadata:
  name: tsugi
  labels:
    app: tsugi
spec:
  template:
    metadata:
      labels:
        app: tsugi
    spec:
      containers:
        - name: web
          image: us.gcr.io/sandbox-199519/tsugi_kube:latest
          ports:
            - containerPort: 80
          env:
          - name: SETUP_GIT
            value: "true"
          - name: TSUGI_WWWROOT
            value: "https://tsugi.lrnxp.net/tsugi"
          - name: TSUGI_SERVICENAME
            value: "TSFUN"
          - name: TSUGI_PDO
            value: "mysql:host=127.0.0.1;dbname=tsugi"
          - name: TSUGI_USER
            valueFrom:
              secretKeyRef:
                name: tsugi-db-credentials
                key: username
          - name: TSUGI_PASSWORD
            valueFrom:
              secretKeyRef:
                name: tsugi-db-credentials
                key: password
          - name: TSUGI_ADMINPW
            valueFrom:
              secretKeyRef:
                name: tsugi-admin-password
                key: password
          volumeMounts:
            - name: my-pvc-nfs
              mountPath: /data
      volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs
      # [END volumes]

